name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # clone the source code containing the package version generation script
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      # make sure python is set up properly
      - name: Install Python (with dependencies)
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install wheel==0.37.1 setuptools==59.6.0 pytest pylint
          python -m pip install -r ./requirements.txt

      - name: Register modules under test
        run: python -m pip install .

      - name: Run tests
        run: python -m pytest tests

      - name: Run linter
        run: python -m pylint pysocialforce
